### ISSUE TITLE
Is it possible to add licence to this repo

### ISSUE THREAD

**Issue by dkwach** [ubiqueIoT/flutter-reactive-ble-example#1]
Hi, I have noticed that this repo has no license so using and redistributing this software can be complicated.
I know that this is example however Scanner or Connector are enough good to just copy them and use it.

Would you consider to add some license file to this repo?

**Comment by epietrowicz** [comment]
Yeah, sorry. All set!

**Comment by dkwach** [comment]
nice and fast - thank you.
Have you thought about making small lib from this?
